site_name: NSI au Lycée Henri Avril
use_directory_urls: false

nav:
  - 'Accueil': 'index.md'
  - 'Structures de données':
    - 'Listes piles et files ' : 'Structure/listes_piles_files.md'
    - 'Programmation Orientée Objet' : 'Structure/POO.md'
    - 'Les graphes' : 'Structure/graphes.md'
    - 'Arbres' : 'Structure/arbres.md'

  - 'Bases de données':
    -  'Modèle relationnel': 'BDD/modele_relationnel.md'
    -  'Langage SQL ' : 'BDD/langageSQL.md'
    -  'Projet SQL ' : 'BDD/projet_SQL.md'
  - 'Programmation':
    -  'Récursivité' : 'Programmation/recursivite.md'
    -  'Modularité' : 'Programmation/modularite.md'
    -  'Projet : Créer un module' : 'Programmation/projet_modularite.md'
    -  'Gestion des Bugs' : 'Programmation/gestion_bug.md'
    -  'Paradigmes de Programmation' : 'Programmation/paradigme_programmation.md'
    -  'Projet : construire un archipel' : 'Programmation/projet_paradigme.md'

  - 'Algorithmie' :
    - 'Arbres Binaires de recherche' : 'algorithmie/ABR.md'
    - 'Diviser pour Régner' : 'algorithmie/diviser.md'
    - 'Recherche textuelle': 'algorithmie/recherche_textuelle.md'
    - 'Programmation dynamique' : 'algorithmie/programmation_dynamique.md'
    -  'Parcours de graphes': 'algorithmie/parcours_graphe.md'
    - 'Calculabilité et décidabilité' : 'algorithmie/calculabilite.md'
  - 'Architecture et OS':
    -  'Sécurisation des communications' : 'archi/crypto.md'
    -  'Et si on codait Enigma?' : 'archi/enigma.md'
    -  'Système sur puce' : 'archi/soc.md'
    -  'Protocoles de routage' : 'archi/routage.md'
    -  'Gestion ds processus' : 'archi/processus.md'


  
  
theme:
  logo: icones/logo4blanc.png
  favicon: icones/logo4.png
  name: material
  font: false
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - admonition
  - meta
  - abbr
  - def_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3



plugins:
  - search
  - macros
#  - markdownmermaid
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      theme_handler_path: theme-handler.py

extra:
  local: G:/info/site_NSI/site/
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/extra.css